name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3'
inputs:

  bucket:
    description: 'The S3 bucket name to deploy to'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the built static files'
    required: true
    default: 'dist'

runs:
  using: 'node16'
  main: 'main.js'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
    - name: 'Install dependencies'
      run: npm install
    - name: 'Build project'
      run: npm run build
    - name: 'Deploy to S3'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}